
import java.awt.Color;
import java.awt.Component;
import java.util.Arrays;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jose Alejandro
 */
public class ClinicaFrame extends javax.swing.JFrame {
    Registro registro;
    ArrayCasillas[][] matriz1;
    Guardia[] array;
    int i;
    /**
     * Creates new form ClinicaFrame
     */
    public ClinicaFrame() {
        initComponents();        
        this.setLocationRelativeTo(null);
        
        matriz1 = new ArrayCasillas[12][30]; //12 columnas (meses) y 30 filas (dias)
        registro = new Registro();
        
        datosIniciales();
        llenarComboBoxes();
        llenarCasillasArray();
    } 
    
    public void datosIniciales(){
        registro.agregarMedico("Juan Perez", "6799652-3", 123456787, 15000, 89098,true);
        registro.agregarEnfermera("Juana Lopez", "563269-K",56432134,6000,2,false);
        registro.agregarMedico("Luis Gutierrez", "8964547-3", 98260, 12000, 98554, false);
        registro.agregarEnfermera("Lidia Mendes","7654376-6",124654,9000,2,true);
        registro.agregarMedico("Eduardo Gonzales", "8786456-6", 561750, 17000, 5653, true);
        registro.agregarEnfermera("Miriam Garcia", "9876456-8", 654101, 8000, 14, false);
        registro.agregarMedico("Guadalupe Torres", "5684873-1", 45101, 17000, 10098, true);
        registro.agregarEnfermera("Lorna Suarez", "4567865-8", 56901, 10000, 12, true);
        registro.agregarMedico("Maria Castillo", "8765485-7", 569101, 13000, 67965, false);
        registro.agregarEnfermera("Mariela Rodriguez", "6789654-8", 320101, 8000, 2, false);
    }
    
    public void llenarComboBoxes(){
        String [] a;
        String [] b;
        a=registro.ListarDPIEnfermeras();
        b=registro.ListarDPIMedicos();
        for (int i = 0; i < a.length; i++) {
            jComboBox3.addItem(a[i]);
            jComboBoxNITEnfermera.addItem(a[i]);
        }
        for (int i = 0; i < b.length; i++) {
            jComboBoxNITMedico.addItem(b[i]);
            
        }
    }
    
    public void getPosiciones(){
        int x=0,y=0;
        x=jTable1.getSelectedRow();
        y=jTable1.getSelectedColumn()-1;
        System.out.println("Filas: "+x+" , Columna:"+y);
    }
    public int getTablaColumns(){
        int y=0;
        y=jTable1.getSelectedColumn()-1;
        return y;
    }
    
    public int getTablaFilas(){
        int x=0;
        x=jTable1.getSelectedRow();
        return x;
    }
    
    /**
     * Metodo que mete un objeto de tipo ArrayCasillas que representa un array de tipo guardia en cada una
     * de las casillas de la matriz1, que en cada casilla puede contener a un medico y a una enfermera.
     */
    public void llenarCasillasArray(){       
        for (int i = 0; i < matriz1.length; i++) {
            for (int j = 0; j < matriz1[i].length; j++) {
                ArrayCasillas array = new ArrayCasillas();
                //array = matriz1[j][i]; //Comienza en la columna enero y recorre todas las filas (dia) de esa 
                                        //columna antes de pasar a la otra columna.
                Guardia enfmed = new Guardia();
                for(int e = 0; e<array.getArrayCasilla().length;e++){
                    //enfmed = array.getArrayCasilla()[e];
                    if (e == 0){
                        enfmed = registro.buscarMedicoR();
                        array.getArrayCasilla()[e] = enfmed;
                        
                    }else{
                        enfmed = registro.buscarEnfermeraR();
                        array.getArrayCasilla()[e] = enfmed;
                    }                    
                }
                matriz1[i][j] = array;
            }
        }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxNITEnfermera = new javax.swing.JComboBox<>();
        jComboBoxNITMedico = new javax.swing.JComboBox<>();
        jButtonBuscarParejas = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButtonEnfermeraGuardia = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonVerGuardia = new javax.swing.JButton();
        jButtonGuardiasTotalesExtras = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButtonSustituirEnfemera = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+28f));
        jLabel1.setText("Clínica La Asunción");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 407, 33));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"2", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"3", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"4", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"5", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"6", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"7", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"8", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"9", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"10", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"11", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"12", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"13", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"14", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"15", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"16", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"17", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"18", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"19", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"20", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"21", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"22", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"23", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"24", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"25", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"26", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"27", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"28", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"29", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia"},
                {"30", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", "Guardia", null}
            },
            new String [] {
                "Día / Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 870, 240));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Control de Guardias");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Busqueda Parejas");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("NIT Enfermera");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("NIT Medico");

        jComboBoxNITEnfermera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));

        jComboBoxNITMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"" }));

        jButtonBuscarParejas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonBuscarParejas.setText("Buscar");
        jButtonBuscarParejas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarParejasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonBuscarParejas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxNITEnfermera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jComboBoxNITMedico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(44, 44, 44))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxNITEnfermera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxNITMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBuscarParejas)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonEnfermeraGuardia.setText("Enfermera con más Guardias");
        jButtonEnfermeraGuardia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnfermeraGuardiaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Opciones Generales");

        jButtonVerGuardia.setText("Información Guardia");
        jButtonVerGuardia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerGuardiaActionPerformed(evt);
            }
        });

        jButtonGuardiasTotalesExtras.setText("Calcular pago Guardias Extras");
        jButtonGuardiasTotalesExtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardiasTotalesExtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonGuardiasTotalesExtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(jButtonEnfermeraGuardia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVerGuardia, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVerGuardia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnfermeraGuardia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGuardiasTotalesExtras, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel7.setText("Sustituir Enfermera");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("NIT Enfermera");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));

        jButtonSustituirEnfemera.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSustituirEnfemera.setText("Sustituir");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSustituirEnfemera, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(45, 45, 45))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSustituirEnfemera)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 860, 170));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, -1, 475));

        jButtonSalir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 0, 137, 46));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVerGuardiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerGuardiaActionPerformed
        // TODO add your handling code here:
        int columnas = getTablaColumns();int meses = columnas+1;
        int filas = getTablaFilas(); int dias = filas+1;
        System.out.println("col: "+columnas+" fil: "+filas);
        ArrayCasillas casilla = new ArrayCasillas();
        casilla = matriz1[columnas][filas];
        Guardia enfmed = new Guardia();
        
        textAreaFrame tframe = new textAreaFrame();
        tframe.setTitle("Guardia de dia:"+dias+", Mes: "+meses);
        //tframe.jTextArea1.append("Guardia de dia:"+dias+", Mes: "+meses);
        for(int i = 0;i<casilla.getArrayCasilla().length;i++){
            enfmed = casilla.getArrayCasilla()[i];
            if((i == 0)&&(enfmed instanceof Medico)){
                tframe.jTextArea1.append(System.getProperty("line.separator"));
                tframe.jTextArea1.append("Medico:");
                tframe.jTextArea1.append(System.getProperty("line.separator"));
                tframe.jTextArea1.append("Nombre: "+enfmed.getNombre());
                tframe.jTextArea1.append(System.getProperty("line.separator")); 
                tframe.jTextArea1.append("NIT: "+enfmed.getNit());
                tframe.jTextArea1.append(System.getProperty("line.separator")); 
                tframe.jTextArea1.append("DPI: "+enfmed.getDpi());
                tframe.jTextArea1.append(System.getProperty("line.separator")); 
                tframe.jTextArea1.append("Salario: "+enfmed.getSalario());
                tframe.jTextArea1.append(System.getProperty("line.separator")); 
                tframe.jTextArea1.append("Colegiado: "+((Medico) enfmed).getColegiado());
                tframe.jTextArea1.append(System.getProperty("line.separator")); 
                tframe.jTextArea1.append("Especialidad: "+((Medico) enfmed).getEspecialista());   
            }else if((i == 1)&&(enfmed instanceof Enfermera)){
                tframe.jTextArea1.append(System.getProperty("line.separator"));
                tframe.jTextArea1.append(System.getProperty("line.separator"));
                tframe.jTextArea1.append("Enfermera:"); 
                tframe.jTextArea1.append(System.getProperty("line.separator"));
                tframe.jTextArea1.append("Nombre: "+enfmed.getNombre());
                tframe.jTextArea1.append(System.getProperty("line.separator")); 
                tframe.jTextArea1.append("NIT: "+enfmed.getNit());
                tframe.jTextArea1.append(System.getProperty("line.separator")); 
                tframe.jTextArea1.append("DPI: "+enfmed.getDpi());
                tframe.jTextArea1.append(System.getProperty("line.separator")); 
                tframe.jTextArea1.append("Salario: "+enfmed.getSalario()); 
                tframe.jTextArea1.append(System.getProperty("line.separator")); 
                tframe.jTextArea1.append("Años de Experiencia: "+((Enfermera)enfmed).getAnos());
                tframe.jTextArea1.append(System.getProperty("line.separator")); 
                tframe.jTextArea1.append("Intensivista: "+((Enfermera)enfmed).getIntensivista());
            }
        }
        tframe.setVisible(true);
    }//GEN-LAST:event_jButtonVerGuardiaActionPerformed
/**
 * este metodo de boton lo que hace es calcular a la enfermera SUPREMA
 * @param evt 
 */
    private void jButtonEnfermeraGuardiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnfermeraGuardiaActionPerformed
        // TODO add your handling code here:
        ArrayCasillas casilla = new ArrayCasillas();
        Guardia enfmed = new Guardia();
        Guardia t=null;
        Enfermera e=null;
        int e1=0,e2=0,e3=0,e4=0,e5=0;
        for (int n = 0; n < matriz1.length; n++) {
            for (int j = 0; j < matriz1[n].length; j++) {
               casilla=matriz1[n][j];
                for(int i = 0;i<casilla.getArrayCasilla().length;i++){
                    t=casilla.getArrayCasilla()[1];
                    if (t instanceof Enfermera) {
                        if ((t.getNit().equals("563269-K"))&&(((Enfermera) t).getIntensivista()==true)) {
                            e1++;
                        }
                        else if ((t.getNit().equals("7654376-6"))&&(((Enfermera) t).getIntensivista()==true)) {
                            e2++;
                        }
                        else if ((t.getNit().equals("9876456-8"))&&(((Enfermera) t).getIntensivista()==true)) {
                            e3++;
                        }
                        else if ((t.getNit().equals("4567865-8"))&&(((Enfermera) t).getIntensivista()==true)) {
                            e4++;
                        }
                        else if ((t.getNit().equals("6789654-8"))&&(((Enfermera) t).getIntensivista()==true)) {
                            e5++;
                        }
                    }
                    
                }
            }
        }
        double mayor=0;
        double extras=0;
        Guardia ee=null;
        if (e2>e4) {
            mayor=(e2-48)*1.0;
            extras=mayor*500.00;
            ee=registro.buscarEnfermeraNIT("7654376-6");
            System.out.println(""+e2);
            JOptionPane.showMessageDialog(null, "El nombre de la enfermera suprema es: "+ee.getNombre()+" hizo un total de "+mayor+" horas de guardias extra y su pago extra por guardias es de: Q"+extras);
        } else if (e2<e4) {
            mayor=(e4-48)*1.0;
            extras=mayor*500.00;
            ee=registro.buscarEnfermeraNIT("4567865-8");
            System.out.println(""+e4);
            JOptionPane.showMessageDialog(null, "El nombre de la enfermera suprema es: "+ee.getNombre()+" hizo un total de "+mayor+" horas de guardias extra y su pago extra por guardias es de: Q"+extras);
        }else if (e2==e4) {
            mayor=(e2-48)*1.0;
            extras=mayor*500.00;
            ee=registro.buscarEnfermeraNIT("4567865-8");
            System.out.println(""+e2);
            JOptionPane.showMessageDialog(null, "Por alguna razon 2 enfermeras quedaron empatadas e hicieron un total de "+mayor+" horas extra, aun así ambas reciben un pago extra por guardias  de: Q"+extras);
            
        }
        
        

    }//GEN-LAST:event_jButtonEnfermeraGuardiaActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonGuardiasTotalesExtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardiasTotalesExtrasActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        ArrayCasillas casilla = new ArrayCasillas();
        Guardia enfmed = new Guardia();
        Guardia t=null;
        int e1=0,e2=0,e3=0,e4=0,e5=0;
        int m1=0,m2=0,m3=0,m4=0,m5=0;
        for (int n = 0; n < matriz1.length; n++) {
            for (int j = 0; j < matriz1[n].length; j++) {
               casilla=matriz1[n][j];
                for(int i = 0;i<casilla.getArrayCasilla().length;i++){
                    t=casilla.getArrayCasilla()[i];
                    if (t instanceof Enfermera) {
                        if ((t.getNit().equals("563269-K"))) {
                            e1++;
                        }
                        else if ((t.getNit().equals("7654376-6"))) {
                            e2++;
                        }
                        else if ((t.getNit().equals("9876456-8"))) {
                            e3++;
                        }
                        else if ((t.getNit().equals("4567865-8"))) {
                            e4++;
                        }
                        else if ((t.getNit().equals("6789654-8"))) {
                            e5++;
                        }
                    } else if (t instanceof Medico) {
                        if ((t.getNit().equals("6799652-3"))) {
                            m1++;
                        }
                        else if ((t.getNit().equals("8964547-3"))) {
                            m2++;
                        }
                        else if ((t.getNit().equals("8786456-6"))) {
                            m3++;
                        }
                        else if ((t.getNit().equals("5684873-1"))) {
                            m4++;
                        }
                        else if ((t.getNit().equals("8765485-7"))) {
                            m5++;
                        }
                    }
                    
                }
            }
        }
      double totale=1.0*(e1+e2+e3+e4+e5);
      double totalm=1.0*(m1+m2+m3+m4+m5);
       double extrase=(totale-240.0);
      double extrasm=totalm-120.0;
      double gtotale=extrase*500;
      double gtotalm=extrasm*900;
      double totals=gtotale+gtotalm;
      JOptionPane.showMessageDialog(null, "El total de horas extras de Enfermeras es de "+extrase+", el total de horas extras de Médicos es de: "+extrasm+" y el pago a darse por horas extras es de: Q"+totals);
      
    }//GEN-LAST:event_jButtonGuardiasTotalesExtrasActionPerformed

    private void jButtonBuscarParejasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarParejasActionPerformed
        // TODO add your handling code here:
        String a="",b="",aa="",bb="",nombree="",nombrem="";
        try {
            a=(String) jComboBoxNITEnfermera.getSelectedItem();// se selecciona el valor del item de el Combobox de enfermera
            b=(String) jComboBoxNITMedico.getSelectedItem();
            if ((a=="")||(b=="")) {
                JOptionPane.showMessageDialog(null, "Para poder buscar debe seleccionar 2 NIT, no solamente uno. Falta un NIT.");
            }
            else{
                ArrayCasillas casilla = new ArrayCasillas();
                Guardia enfmed = new Guardia();
                Guardia t=null;
                int e1=0;
                for (int n = 0; n < matriz1.length; n++) {
                    for (int j = 0; j < matriz1[n].length; j++) {
                       casilla=matriz1[n][j];
                        for(int i = 0;i<casilla.getArrayCasilla().length;i++){
                            t=casilla.getArrayCasilla()[i];
                            if (t instanceof Enfermera) {
                               aa=t.getNit();
                               
                            }else if (t instanceof Medico) {
                               bb=t.getNit();
                               
                            }
                        }
                        if ((a.equals(aa))&&(b.equals(bb))) {
                            e1++;
                        }
                    }
                }
                Guardia s=null;
                Guardia d=null;
                s=registro.buscarEnfermeraNIT(a);
                d=registro.buscarMedicoNIT(b);
                JOptionPane.showMessageDialog(null, "La cantidad de veces que la enfermera "+s.getNombre()+" con numero de NIT:"+a+" y el médico "+d.getNombre()+" con numero de NIT:"+b+" estuvieron juntos de guardia es de: "+e1);
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Seleccione un NIT de Enfermera y un Nit de Medico Valido");
        }
    }//GEN-LAST:event_jButtonBuscarParejasActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClinicaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClinicaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClinicaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClinicaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClinicaFrame().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarParejas;
    private javax.swing.JButton jButtonEnfermeraGuardia;
    private javax.swing.JButton jButtonGuardiasTotalesExtras;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSustituirEnfemera;
    private javax.swing.JButton jButtonVerGuardia;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBoxNITEnfermera;
    private javax.swing.JComboBox<String> jComboBoxNITMedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
